#!/usr/bin/env python

from ConfigParser import SafeConfigParser
from bs4 import BeautifulSoup as soupy
from timeit import default_timer

import argparse
import logging
import nagiosplugin
import os
import requests

"""
Attempts to log in to CAS.
"""

def login_elements(tag):
    """A filter to find cas login form elements"""
    return tag.has_key('name') and tag.has_key('value')

class Timer(object):

    def __init__(self):
        self.timer = default_timer

    def __enter__(self):
        self.start = self.timer()
        return self

    def __exit__(self, *args):
        end = self.timer()
        self.elapsed_secs = (end - self.start)

class CasLogin(nagiosplugin.Resource):
    
    def __init__(self, config_dict):
        self.url         = config_dict['url']
        self.username    = config_dict['username']
        self.password    = config_dict['password']
        self.success_txt = config_dict['success_txt']

    def probe(self):
        with Timer() as init_timing:
            page = requests.get(self.url)

        cas_doc = soupy(page.text)
        form_inputs = cas_doc.find_all(login_elements)

        login_data = dict()
        for tag in form_inputs:
            login_data[tag['name']] = tag['value']

        login_data['username'] = self.username
        login_data['password'] = self.password

        with Timer() as login_timing:
            page = requests.post(self.url, login_data, cookies=page.cookies)

        if self.success_txt in page.text:
            yield nagiosplugin.Metric('cas_page_load',
                                      init_timing.elapsed_secs,
                                      uom='s',
                                      context='CAS')
            yield nagiosplugin.Metric('cas_login',
                                      login_timing.elapsed_secs,
                                      uom='s',
                                      context='CAS')

def parse_config(config_file, section, keys):
    """Returns a dict with the keys of in section@config_file."""
    parser = SafeConfigParser()
    parser.read(os.path.abspath(config_file))
    configuration = dict()
    for k in keys:
        configuration[k] = parser.get(section, k)
    return configuration

# guarded ensures the script always exits with a nagios-friendy return
@nagiosplugin.guarded
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-w', '--warning', metavar='milliseconds',
                        help='CAS is warning if response time is > n ms.')
    parser.add_argument('-c', '--critical', metavar='milliseconds',
                        help='CAS is critical if response time is > n ms.')
    parser.add_argument('-v', '--verbose', action='count', default=0,
                        help='add Vs for more verbosity.')
    parser.add_argument('--extra-opts', type=str,
                        default='cas_check@/etc/nagios/private/custom.ini',
                        help='Look for username and password in section@/ini/file/path.ini')

    args = parser.parse_args()

    # split the section from the file name
    config_section, config_file = args.extra_opts.split('@')

    config = parse_config(config_file,
                          config_section,
                          [
                            'username',
                            'password',
                            'success_txt',
                            'url',
                          ])
    cas = CasLogin(config)
    for result in cas.probe():
        print result

if __name__ == '__main__':
    main()
